=== yulin2/atlas/src/test/resources/TVListings.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited by Gary Bielby "PA" Listings -->
<!-- listings Radio Times DTD v2.10 20/08/2013 mj -->


<!ELEMENT tv_data (listings_date+)>


<!-- the TV listings for a particular date
	date: the date of the listings in the form DD/MM/YYYY, where YYYY indicates the year, MM indicates the month and DD indicates the day -->
<!ELEMENT listings_date (channel_data+)>
<!ATTLIST listings_date
	date CDATA #REQUIRED
>


<!-- the data for a particular TV channel
name: the name of the TV channel
channel_id: the id of the TV channel
start_time: the starttime of the channel in xsd:dateTime format. The first prog_data element will start on or after this time.
end_time: the endtime of the channel in xsd:dateTime format. The last prog_data element will start before this time.
-->
<!ELEMENT channel_data (channel_logo?, epgdetails?, prog_data+)>
<!ATTLIST channel_data 
	name CDATA #REQUIRED
	channel_id CDATA #REQUIRED
	start_time CDATA #REQUIRED
	end_time CDATA #REQUIRED
>

<!-- channel logo -->

<!ELEMENT channel_logo (#PCDATA)>
<!ATTLIST channel_logo
	width CDATA #REQUIRED 
	height CDATA #REQUIRED 
>

<!-- epg data -->
<!ELEMENT epgdetails (epg+)>

<!-- epg data from one provider
provider_id: a unique id for this provider
provider_name: the name of the epg provider
channel_number: the channel_number of the current channel for this provider
-->

<!ELEMENT epg EMPTY>
<!ATTLIST epg
  provider_id CDATA #REQUIRED
  provider_name CDATA #REQUIRED
  channel_number CDATA #REQUIRED
>


<!-- the data for a TV programme -->
<!ELEMENT prog_data (showing_id, prog_id, series_id?, series_synopsis?, series_summary?, series_version?, season?, rt_filmnumber?, date, time, duration, group?, title, episode_title?, programme_version?, episode_number?, episode_total?, series_number?, category*, rt_category?, film_year?, genre?, certificate?,country?,colour?,warning?,subtitles?,dubbing?,star_rating?, cast_member*, staff_member*, billings?, videoplus, attr, rovi_genre? ,rovi_description?, links?, pictures?)>

<!-- generic: This is a generic episode -->
<!ATTLIST prog_data
	generic CDATA #IMPLIED
>



<!-- The id of a showing of a programme on a particular channel. If the time of a showing changes, the showing_id remains the same -->
<!ELEMENT showing_id (#PCDATA)>

<!-- The id of a programme. Different showings of the same programme have the same prog_id. E.g. all showings of a particular episode of Friends have the same prog_id -->
<!ELEMENT prog_id (#PCDATA)>

<!-- The id of a series. E.g. all episodes of Friends have the same series_id -->
<!ELEMENT series_id (#PCDATA)>

<!-- String containing synopsis of series -->
<!ELEMENT series_synopsis (#PCDATA)>

<!-- String containing summary of series -->
<!ELEMENT series_summary (#PCDATA)>


<!-- String to help clarify exactly which series this is in cases where there are other series or programmes with the same title -->
<!ELEMENT series_version (#PCDATA)>

<!-- Season Information -->
<!ELEMENT season (season_title?, season_summary?)>
<!-- id: Unique id for this season -->
<!-- number: The season number -->
<!ATTLIST season
	id CDATA #REQUIRED
	number CDATA #IMPLIED
>

<!-- The Season Title -->
<!ELEMENT season_title (#PCDATA)>

<!-- The Season Summary -->
<!ELEMENT season_summary (#PCDATA)>


<!-- programme broadcast date in the form DD/MM/YYYYY, where YYYY indicates the year, MM indicates the month and DD indicates the day -->
<!ELEMENT date (#PCDATA)>


<!-- programme broadcast time in the form hh:mm where hh indicates the hour, mm indicates the minute -->
<!ELEMENT time (#PCDATA)>


<!-- programme duration in minutes -->
<!ELEMENT duration (#PCDATA)>

<!-- the name of the group this programme belongs to if any -->
<!ELEMENT group (#PCDATA)>

<!-- programme title -->
<!ELEMENT title (#PCDATA)>


<!-- episode title -->
<!ELEMENT episode_title (#PCDATA)>

<!-- String to help clarify exactly which programme this is in cases where there are other programmes or series with the same title -->
<!ELEMENT programme_version (#PCDATA)>

<!-- episode number -->
<!ELEMENT episode_number (#PCDATA)>

<!-- total number of episodes in the series -->
<!ELEMENT episode_total (#PCDATA)>

<!-- series number -->
<!ELEMENT series_number (#PCDATA)>

<!-- rt filmnumber internal ref used by RT -->
<!ELEMENT rt_filmnumber (#PCDATA)>

<!-- programme category -->
<!ELEMENT category (category_name, category_code)>

<!-- RT category -->
<!ELEMENT rt_category (maincat, subcat?)>

<!-- RT Main category -->
<!ELEMENT maincat (#PCDATA)>

<!-- RT Subcategory -->
<!ELEMENT subcat (#PCDATA)>

<!-- programme category name -->
<!ELEMENT category_name (#PCDATA)>

<!-- programme category code -->
<!ELEMENT category_code (#PCDATA)>


<!-- film year (films only) -->
<!ELEMENT film_year (#PCDATA)>


<!-- film certificate (films only) -->
<!ELEMENT certificate (#PCDATA)>

<!-- genre -->
<!ELEMENT genre (#PCDATA)>

<!-- subtitles -->
<!ELEMENT subtitles (#PCDATA)>

<!-- country (films only) -->
<!ELEMENT country (#PCDATA)>

<!-- colour (films only) -->
<!ELEMENT colour (#PCDATA)>

<!-- warning  such as contains strong language -->
<!ELEMENT warning (#PCDATA)>

<!ATTLIST warning
  type CDATA #REQUIRED
>

<!-- Rovi Genre -->
<!ELEMENT rovi_genre (#PCDATA)>

<!-- Rovi Description -->
<!ELEMENT rovi_description (#PCDATA)>


<!-- dubbing  e.g this programme is dubbed in Welsh -->
<!ELEMENT dubbing (#PCDATA)>

<!-- star rating -->
<!ELEMENT star_rating (#PCDATA)>

<!-- cast member -->
<!ELEMENT cast_member (character?, actor?)>

<!-- character in a programme -->
<!ELEMENT character (#PCDATA)>

<!-- production staff member -->
<!ELEMENT staff_member (role, person)>

<!-- production staff role -->
<!ELEMENT role (#PCDATA)>

<!-- an actor in the cast 
person_id: A unique id for this person
-->
<!ELEMENT actor (#PCDATA)>
<!ATTLIST actor
	person_id CDATA #REQUIRED
>

<!-- name of member of the production staff 
person_id: A unique id for this person
-->
<!ELEMENT person (#PCDATA)>
<!ATTLIST person
	person_id CDATA #REQUIRED
>
<!-- programme synopsis 
	programme billings such as synopsis, extra detail and x-refs
-->
<!ELEMENT billings (billing+)>

<!--- billing field 
-->
<!ELEMENT billing (#PCDATA)>
<!ATTLIST billing
	type CDATA #REQUIRED
	reviewer_initials CDATA #IMPLIED
	reviewer_name CDATA #IMPLIED
>

<!ELEMENT videoplus (#PCDATA)>

<!-- programme attributes 
	stereo: the programme in stereo.
	subtitles: the programme carries Teletext or Ceefax subtitles.
	repeat: the programme a repeat.
	bw: the programme broadcast in Black and White.
	premiere: this a broadcast premiere.
    new_episode: this is the first showing of this programme on this channel.
    new_series: this is the first episode of a news series of this programme.
	last_in_series: this is the last in a series of showings of this programme.
	surround: the programme is being broadcast in surround sound.
	widescreen: the programme being shown in widescreen format.
	film: the programme a film.
	sign_lang: the programme have sign language.
	in_vision:  the programme has in vision subtitles.
	audio_des: the programme is audio described.
	interactive: the programme has interactive content.
	hd: the programme is also showing on the High Definition channel
	live: this is a live broadcast
	as_live: this programme is being shown as-live
	follow_on: this is a follow_on programme. (The programme follows the previous 
	programme but doesn't have an exact broadcast time). In the xml, the time
	field will contain the time of the previous programme. 
	tv_movie: this programme is a made-for-tv movie
	web_choice: RT web choice
	special: this programme is part of a series but should generally be referred to by the episode title rather than the series title. E.g. "The X-Factor Live Final", "Never Mind the Buzzcocks Christmas Special". E.g. if displaying these programmes on a schedule list, the episode titles should be prominent. 
	three_d: the programme employs techniques of 3D presentation.
	 
-->
<!ELEMENT attr EMPTY>
<!ATTLIST attr
	stereo (yes | no) "no"
	subtitles (yes | no) "no"
	repeat (yes | no) "no"
	bw (yes | no) "no"
	premiere (yes | no) "no"
	new_episode (yes | no) "no"
	new_series (yes | no) "no"
	last_in_series (yes | no) "no"
	surround (yes | no) "no"
	widescreen (yes | no) "no"
	film (yes | no) "no"
	sign_lang (yes | no) "no"
	in_vision (yes | no) "no"
	audio_des (yes | no) "no"
	interactive (yes | no) "no"
	hd (yes | no) "no"
	live (yes | no) "no"
	as_live (yes | no) "no"
	follow_on (yes | no) "no"
	choice (yes | no) "no"
	familychoice (yes | no) "no"
	tv_movie (yes | no) "no"
	web_choice (yes | no) "no"
	special (yes | no) "no"
	three_d (yes | no) "no"
>


<!-- Element containing a list links for this showing -->
<!ELEMENT links ( link+ )>

<!ELEMENT link (#PCDATA)>
<!ATTLIST link type (Website | Twitter | email | Phone | Text | Contact) #REQUIRED>


<!-- Element containing list of pictures for this showing -->
<!ELEMENT pictures ( pictureUsage+ )>


<!-- Name of image file. Attributes (see below) describe usage of image for this showing. -->
<!ELEMENT pictureUsage ( #PCDATA )>


<!-- pictureUsage attributes
	pictureUsage_id: unique ID for this image for this showing
	copyright: Copyright information for this image.
	type: Indicates whether picture content refers to this specific episode,
				season or the whole series. 
	start_date: date from which this picture can be used alongside this showing.
	expiry_date: last date on which picture can be used alongside this showing.
-->

<!ATTLIST pictureUsage
 pictureUsage_id CDATA #REQUIRED
 copyright CDATA #REQUIRED 
 type ( episode | season | series ) #REQUIRED
 start_date CDATA #IMPLIED
 expiry_date CDATA #IMPLIED
>

=== yulin2/atlas/src/test/resources/20110115_tvdata.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tv_data SYSTEM "TVListings.dtd">
<tv_data>
  <listings_date date="15/01/2011">
    <channel_data name="BBC1" channel_id="4" start_time="2011-01-15T06:00:00+00:00" end_time="2011-01-16T06:00:00+00:00">
      <epgdetails>
        <epg provider_id ="6" provider_name="Virgin TV (Telewest)" channel_number="101"/>
        <epg provider_id ="11" provider_name="Sky NI" channel_number="101"/>
        <epg provider_id ="7" provider_name="Freeview Wales" channel_number="1"/>
        <epg provider_id ="2" provider_name="Virgin TV (NTL)" channel_number="101"/>
        <epg provider_id ="12" provider_name="Freesat" channel_number="101"/>
        <epg provider_id ="8" provider_name="NTL Ireland Digital" channel_number="108"/>
        <epg provider_id ="1" provider_name="Sky" channel_number="101"/>
        <epg provider_id ="4" provider_name="Freeview" channel_number="1"/>
        <epg provider_id ="10" provider_name="Sky Wales" channel_number="101"/>
        <epg provider_id ="5" provider_name="Topup" channel_number="1"/>
      </epgdetails>
      <prog_data>
        <showing_id>71118471</showing_id>
        <prog_id>1424497</prog_id>
        <series_id>122139</series_id>
          <date>15/01/2011</date>
        <time>21:40</time>
        <duration>30</duration>
        <title>Come Fly with Me</title>
        <episode_number>2</episode_number>
        <episode_total>6</episode_total>
        <series_number>1</series_number>
        <category><category_name>Comedy</category_name><category_code>1400</category_code></category>
        <rt_category><maincat>Comedy</maincat></rt_category>
        <cast_member>
            <character>Various characters</character>
            <actor person_id="1">Matt Lucas</actor>
        </cast_member>
        <cast_member>
            <character>Various characters</character>
            <actor person_id="2">David Walliams</actor>
        </cast_member>
        <cast_member>
            <character>Holly&apos;s mother</character>
            <actor person_id="3">Rebecca Humphries</actor>
        </cast_member>
        <cast_member>
            <character>Mrs Talbot</character>
            <actor person_id="4">Di Botcher</actor>
        </cast_member>
        <cast_member>
            <character>Posh lady</character>
            <actor person_id="5">Louisa Rix</actor>
        </cast_member>
        <cast_member>
            <character>African lady</character>
            <actor person_id="6">Ellen Thomas</actor>
        </cast_member>
        <cast_member>
            <character>Happy Burger customer</character>
            <actor person_id="7">Paul Putner</actor>
        </cast_member>
        <cast_member>
            <character>Drunk pilot</character>
            <actor person_id="8">Ted Robbins</actor>
        </cast_member>
        <cast_member>
            <character>Duty free passsenger</character>
            <actor person_id="9">Liz Sutherland</actor>
        </cast_member>
        <cast_member>
            <character>Passenger</character>
            <actor person_id="10">Laurence Howarth</actor>
        </cast_member>
        <cast_member>
            <character>Hand luggage woman</character>
            <actor person_id="11">Claire Vousden</actor>
        </cast_member>
        <cast_member>
            <character>Nervous passenger</character>
            <actor person_id="12">Selina Griffiths</actor>
        </cast_member>
        <cast_member>
            <character>Elderly man</character>
            <actor person_id="13">Freddie Lees</actor>
        </cast_member>
        <cast_member>
            <character>FlyLo employee</character>
            <actor person_id="14">Pippa Bennett-Warner</actor>
        </cast_member>
        <staff_member>
          <role>Director</role>
          <person person_id="15">Paul King</person>
        </staff_member>
        <staff_member>
          <role>Producer</role>
          <person person_id="16">Adam Tandy</person>
        </staff_member>
        <staff_member>
          <role>Writer</role>
          <person person_id="17">Matt Lucas</person>
        </staff_member>
        <billings>
          <billing type="synopsis">FlyLo passengers are delayed on a journey to Malaga when there is a wing malfunction on their flight, while Melody and Taaj get tough with the airline&apos;s new baggage allowance policy. Pete and Judith explain what went wrong on their cruise, and there is an introduction to Happy Burger&apos;s newest employee and pilot-to-be Tommy. Comedy, with Matt Lucas and David Walliams.</billing>
          <billing type="pa_detail1">A wing malfunction delays passengers.</billing>
          <billing type="pa_detail2">FlyLo passengers are delayed on a journey to Malaga when there is a wing malfunction on their flight, while Melody and Taaj get tough with the new baggage allowance policy.</billing>
          <billing type="pa_detail3">FlyLo passengers are delayed on a journey to Malaga when there is a wing malfunction on their flight, while Melody and Taaj get tough with the airline&apos;s new baggage allowance policy. Pete and Judith explain what went wrong on their cruise, and there is an introduction to Happy Burger&apos;s newest employee and pilot-to-be Tommy. Comedy, with Matt Lucas and David Walliams.</billing>
        </billings>
<videoplus>399370</videoplus><attr stereo="no" subtitles="yes" repeat="yes" bw="no" premiere="no" new_series="no" last_in_series="no" surround="no" widescreen="yes" film="no" sign_lang="no" in_vision="no" audio_des="yes" interactive="no" hd="yes" live="no" as_live="no" follow_on="no" choice="no" familychoice="no" tv_movie="no" web_choice="no" three_d="yes"/>
        <pictures>
          <pictureUsage type="season" pictureUsage_id="75455-71118471" copyright="©BBC" start_date="18/12/2010" expiry_date="05/02/2011">webcomeflywithme1.jpg</pictureUsage>
          <pictureUsage type="season" pictureUsage_id="75456-71118471" copyright="©BBC" start_date="18/12/2010" expiry_date="05/02/2011">webcomeflywithme2.jpg</pictureUsage>
        </pictures>
      </prog_data>
    </channel_data>
  </listings_date>
</tv_data>
